#!/usr/bin/env bash

# Detect the script location, so it doesn't need to be ran from a specific folder to work.

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

set -e

# Load Common Settings


if [ $# -lt 2 ]; then
    echo "Usage: $0 <profile> <command...>" >&2
    exit 1
fi

source "${DIR}/bash_include.sh"
docker-env "$1"

shift

$@
